CSC-3380-Spring-2025/Team-19

Word_Ladder.py

Created the Word Ladder branch off of dev and committed and pushed the basic code for the game.

Word Ladder Branch and Code

---

Wheel_Of_Fortune.py

Created the Wheel Of Fortune branch off of dev and committed and pushed the basic code for the game.

Wheel of Fortune branch and Code

---

src/ConnectionsGame.py

Created the Connections branch off of dev and committed and pushed the basic code for the game.

Connections branch and Code

---

src/HowToPlay.py

How to play pop ups are created in a python file and user's data related to opening each game for the first time is stored locally in a json file.

Creates Code for How to Play Pop Ups

---

src/Database.py
src/requests.py

https://github.com/CSC-3380-Spring-2025/Team-19/issues/43

Added type hints where necessary

---

src/ConnectionsGame.py
src/Wheel_Of_Fortune.py
src/Word_Ladder.py

I changed 3 files in dev, ConnectionsGame.py, Word_Ladder.py, and Wheel_Of_Fortune.py, removing their test calls and adding in a separate testing function within each of them.

Bug Fix: Remove and Replace Testing Calls

---

src/Timer_Func.py

Timer function for the games.
Timer_Func.py

Create Basic Function for Timed Feature of the Games

---

lib/connections.dart

Increased the size of the box containing the words for the Connections game so that all words fit on screen at the same time. Adjusted other sizes to fit everything while still maintaining good ratios.

Minor Bug Fix: Fix Connections Game Word Display

---

lib/connections.dart

Fixed the size issue with the current version of the Connections game. Due to the continued development of the games, this will not be the last time that sizes will need to be adjusted.

Connections Size Fix 

---

lib/connections_leaderboard_page.dart
lib/home_page.dart
lib/leaderboard_selector.dart
lib/letterquest_leaderboard_page.dart
lib/main.dart
lib/wordladder_leaderboard_page.dart

Created a leaderboard page for each game as well as a leaderboard selector page. 
I've also changed main.dart to connect to a now functioning version of the home page, with working "Play" and "Daily Leaderboard" buttons.

Create Leaderboard Feature

---

lib/connections.dart

Added in code for a congratulatory popup if the player wins the Connections game that also displays their score. Note, once the timer feature is finished, the score calc will need to be changed to reflect the timer.

Create Win Pop Up for Connections

---

lib/letterquest.dart

Fixed the Letter Quest game to now have on onscreen, functional keyboard. Note that enter and delete functionality will need to be added in once the game is more fully developed (there is letter_quest_input.dart, but it's not connected right now).

Minor Bug Fix: Make Keyboard Appear in LetterQuest

---

lib/connections.dart
lib/letterquest.dart
lib/wordladder_frontend.dart

Adds a timer in the top right corner of each game, and adding the amount of seconds passed in calculating the user's score.

Implement Timer Feature into Each Game

---

lib/keyboard_ui.dart
lib/letter_quest_input.dart
lib/letterquest.dart

added solve the puzzle button to letterquest and changed keyboard

Letterquest solve the puzzle

---

lib/letterquest.dart
lib/wordladder_frontend.dart

In LetterQuest and Word Ladder, each have a text box that had a submit guess button. The logic of that button is now implemented in the enter key on the keyboard.

Allows Enter Button to Submit Text Box Answers

---

lib/keyboard_ui.dart
lib/letterquest.dart
pubspec.yaml

Fix Pubspec so code can run, Remove Enter and Delete buttons from LetterQuest keyboard, Spaced out Keyboard from Solve the Puzzle Button

Fix Pubspec, Remove Enter and Delete LetterQuest, Spaced out Keyboard

---

lib/home_page.dart

Adds Pop Up UI, Does Not function, functionality task exists to make this do anything.

Adds Username Pop Up to Home Page

---

lib/home_page.dart

Moved the "Play" and "Daily Leaderboards" on the home screen slightly upwards. This is not related to any tasks, it just bothered me how low down on the screen they were.

Home Screen Size Adjustment

---

lib/letterquest.dart

Letterquest timer wasn't canceling when game was won, that now works.

Fixes LetterQuest Timer to Stop on End of Game

---

lib/connections_leaderboard_page.dart
lib/letterquest_leaderboard_page.dart
lib/wordladder_leaderboard_page.dart

Changed the 3 leaderboard pages to now get their entries by fetching information from the database. The test values for each page have been commented out.

Pull Statistics from Database for Leaderboards

---

lib/data/seed_connections.dart
lib/data/seed_letterquest.dart
lib/data/seed_wordladder.dart
lib/db/databasehelper.dart

Due to there being no real way to test this right now, I am painfully skeptical that I did this right. But in theory, I have created three dart files containing all of the sample game levels for each game, with an ID and their various data. And I have theoretically called these to be added to their respective database tables in the database helper. At the minimum, the sample games now exist, at a best case scenario, they exist inside the database and can be called into the project.

Adds Template Games to Database

---

lib/db/databasehelper.dart
lib/models/user_model.dart

Fixed an infinite looping bug that caused the ok button to not work as well as adjusted the user model to account for JSON's inability to encode maps that do not use strings as keys.

Fixed an infinite looping bug that caused the ok button to not work

---

lib/data/seed_letterquest.dart
lib/letterquest.dart

Calls letterquest data from the database to give phrase and hint inputs. Adds a next level button that resets the game functions and calls new phrase and hint. Fixed a spelling error in letterquest data seed. Fixed a visual error on Win Pop Up when hitting enter button on letterquest game to now show the time the user completed the game in.

Letterquest Levels/Other Letterquest Stuff

---

lib/data/seed_letterquest.dart

Capitalized 5 words that should've been capitalized in the data, missed this by like 5 minutes of my last push.

More Letterquest Seed Data Changes

---

lib/connections.dart
lib/data/seed_connections.dart

Adds game cycle and next level button to scattergories, changes one of the games in the seed data.

Scattergories Game Cycle/Seed Data Fixes

---

lib/data/seed_wordladder.dart
lib/wordladder_frontend.dart

Word Ladder now properly cycles through games, fixed capitalization on seed data for word ladder words.

Game Cycle for WordLadder/WL Seed Data Fixes

---

lib/letterquest.dart

Fixed a null value bug for letterquest win statistics

Fix null value bug

---

lib/connections.dart

Previously, there was a large merge conflict for dev that would require me to run the code to make sure it was resolve.  I believe I've done that here.  Any bugs that arise at the moment were simply unaddressed, though here's a few I noticed off hand:
1. Clicking next level does not remove the previously active game
2. Snackbar popup hides next level button after a win
3. Category colors were defined initially by category name and not their order in the map

Resolved Connections Merge Conflict

---

lib/connections_leaderboard_page.dart
lib/letterquest_leaderboard_page.dart
lib/wordladder_frontend.dart
lib/wordladder_leaderboard_page.dart

Added user score saving to Word Ladder, viewable on the leaderboard

Added db connection to Word Ladder

---

lib/connections.dart

Should fix leaderboard button, solved words don't stick to screen anymore, fixed how to play pop up, optimized snackbar calls.

Fixed Scattergories Hopefully

---

lib/connections.dart

Added leaderboard connections to Scattergories and also adjusted the color to not be hardcoded.

Added db connection and fixed colors

---

lib/connections.dart

Yellow text was too yellow (related pr: #185)

Made the yellow less yellow

---

lib/connections.dart
lib/keyboard_ui.dart
lib/letterquest.dart

This is not related to any tasks. Changed the colors in the Scattergories and LetterQuest game pages, as well as the keyboard in LetterQuest to be more consistent with the rest of the website.

Small Color Fixes

---

lib/connections.dart
lib/connections_leaderboard_page.dart
lib/leaderboard_selector.dart

Put scattergories name where needed

Add Scattergories Name

---

lib/connections.dart
lib/connections_leaderboard_page.dart
lib/letterquest.dart
lib/wordladder_frontend.dart

How to Play Pop Ups can't be dismissed unless hitting ok button, scattergories should finally be everywhere

HTP Barrier Dismissible, Scattergories

---

lib/game_selector.dart
lib/home_page.dart
lib/leaderboard_selector.dart
lib/main.dart
lib/profile_page.dart

Adds Username on Home Page, Leaderboard Selector Page, Game Selector Page, and Reimagines the Profile Page with Username

User everywhere

---

connections.dart
wordladder_frontend.dart

added a little more pizzaz to all the how to play popups similarly to how letterquest's was styled

Stylized How To Play Popups

---

lib/home_page.dart
lib/wordladder_frontend.dart

Adjusted the spacing on the home page and word ladder game, making them now fit properly on tablet and mobile view.

Moderate Bug Fix: Pages Overflow in Tablet and Mobile View

---

letterquest.dart

added a SizedBox for the hint that users will be given to make it more visually appealing

Fixed Hint Spacing

---

lib/data/seed_wordladder.dart
lib/game_selector.dart
lib/leaderboard_selector.dart

Fixed the overflow error in the WordLadder game as well as added in leaderboard notices on both selector screens to avoid any confusion when the instructor/TA tests our website.

Overflow Fix and Leaderboard Notice
